description: >
  Get kubeconfig using cluster ID

parameters:
  cluster_id:
    type: env_var_name
    description: LKE Cluster ID
    default: LINODE_CLUSTER_ID
  linode_token:
    type: env_var_name
    description: Linode API Token
    default: LINODE_TOKEN

steps:
- run:
    name: Check for env vars
    command: |

- run:
    name: Install JQ
    command: |
      if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
      $SUDO apt-get update && $SUDO apt-get install -y jq
- run:
    name: Set up LKE kubeconfig
    command: |
      KUBE_VAR=$( curl -H "Authorization: Bearer $<<parameters.linode_token>>" https://api.linode.com/v4/lke/clusters/${<<parameters.cluster_id>>}/kubeconfig | jq .kubeconfig )
      lke_var="export KUBECONFIG_DATA=$KUBE_VAR"
      echo $lke_var >> $BASH_ENV
- kubernetes/install-kubectl
- kubernetes/install-kubeconfig
