description: >
  Python executor w/ tag
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: lts
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
